"""Prepare self-contained Arduino IDE sketches from the canonical node firmware.

Run ``python3 -m tools.prepare_tracker_firmware`` from the project directory.
Generated sources can be refreshed safely: tracker_config.h is never overwritten.
No boards are contacted or flashed by this command.
"""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIRMWARE = ROOT / "firmware"
DEFAULT_OUTPUT = FIRMWARE / "arduino"
HEADERS = ("settings.h", "wm_protocol.h")
# Node IDs follow box position left to right. With three boxes the right box is
# node 2; a two-box layout uses right_pair (node 1) for its right box.
NODES = (("left", 0), ("middle", 1), ("right", 2), ("right_pair", 1))


BUZZER_SETTINGS = '''
// Buzzer, middle box only: + to GPIO25, - to GND. The laptop sounds it with
// WM2 BUZZ. 2000 Hz square wave for a passive buzzer; set BUZZER_TONE_HZ to 0
// for an active buzzer, which only needs the pin held HIGH.
#define BUZZER_PIN 25
#define BUZZER_TONE_HZ 2000
'''
NO_BUZZER = '''
// No buzzer on this box: only the middle box carries one, on GPIO25.
'''


def config_template(side: str, node_id: int) -> str:
    # By position, not by node ID: right_pair is node 1 as well, but it is the
    # right box of a two-box layout and gets no buzzer here. The PlatformIO
    # build differs: config.example.h sets BUZZER_PIN for NODE_ID 1, so
    # node_right_pair drives GPIO25. Nothing is wired there in either case.
    buzzer = BUZZER_SETTINGS if side == "middle" else NO_BUZZER
    return f'''#pragma once

// Settings for the {side.upper()} ESP32 only. Keep this file private.
// The preparation command preserves this file when refreshing firmware sources.
#define NODE_ID {node_id}

// The one supported network: a phone hotspot (WPA2-personal). The computer and
// every box join it. The ESP32 radio is 2.4 GHz only: on an iPhone turn on
// "Maximise Compatibility" and keep the Personal Hotspot screen open while
// the boxes join.
// An iPhone's default hotspot name contains a typographic apostrophe (U+2019).
// Write it as the UTF-8 bytes \\xE2\\x80\\x99 inside the C string, for example
// "Sam\\xE2\\x80\\x99s iPhone".
#define WIFI_SSID ""
#define WIFI_PASSWORD ""

// Same pin map on every box. GPIO34 is input-only with no internal pull
// resistors; power the sensor from 3V3 and wire ECHO directly (no divider).
#define SERVO_PIN 33
#define ULTRASONIC_TRIG_PIN 32
#define ULTRASONIC_ECHO_PIN 34
{buzzer}
// World bearings: 0 = right, 90 = into the field, 180 = left.
// Check your servo's mounting and specifications before scanning.
// Uploading/restarting centers the servo at a requested bearing of 90 degrees.
#define SERVO_REVERSED 0
#define SERVO_CENTER_TRIM_MDEG 0

// Conservative initial pulse endpoints; calibrate for your actual servo.
// These endpoints map to servo coordinates 0 and 180 degrees.
#define SERVO_PULSE_MIN_US 1000
#define SERVO_PULSE_MAX_US 2000
#define SERVO_MIN_MDEG 0
#define SERVO_MAX_MDEG 180000
'''


def sketch_sources(side: str, node_id: int) -> dict[str, str]:
    """Return generated files; deliberately exclude private/local configuration."""
    name = f"tracker_{side}"
    source = (FIRMWARE / "src" / "main.cpp").read_text(encoding="utf-8")
    files = {
        f"{name}.ino": (
            "// Open this sketch in Arduino IDE; select ESP32 Dev Module.\n"
            "// Edit the tracker_config.h tab, then upload to this node only.\n"
            "// tracker_node.cpp contains setup()/loop(); it is generated from\n"
            "// firmware/src/main.cpp to avoid Arduino's automatic prototypes.\n"
            "// Refresh with: python3 -m tools.prepare_tracker_firmware\n"
            "#include <Arduino.h>\n"
        ),
        "tracker_node.cpp": (
            "// Generated by tools.prepare_tracker_firmware; edit firmware/src/main.cpp.\n"
            '#include "tracker_config.h"\n'
            f'static_assert(NODE_ID == {node_id}, "This is the {side} node sketch");\n\n'
            + source
        ),
    }
    for header in HEADERS:
        files[header] = (FIRMWARE / "include" / header).read_text(encoding="utf-8")
    return files


def prepare(output: Path = DEFAULT_OUTPUT, *, check: bool = False) -> list[Path]:
    """Write sketches, or return missing/stale paths without changes in check mode."""
    changed = []
    for side, node_id in NODES:
        folder = output / f"tracker_{side}"
        for name, content in sketch_sources(side, node_id).items():
            path = folder / name
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                changed.append(path)
                if not check:
                    folder.mkdir(parents=True, exist_ok=True)
                    path.write_text(content, encoding="utf-8")

        # The hotspot name/password and servo settings live here: never overwritten.
        config = folder / "tracker_config.h"
        if not config.exists():
            changed.append(config)
            if not check:
                # Exclusive creation also protects settings if two preparations overlap.
                with config.open("x", encoding="utf-8") as stream:
                    stream.write(config_template(side, node_id))
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT,
                        help="Parent directory for tracker_left, tracker_middle, tracker_right and tracker_right_pair")
    parser.add_argument("--check", action="store_true",
                        help="Check generated sources are current; do not write files")
    args = parser.parse_args(argv)
    output = args.output_dir.resolve()
    try:
        changed = prepare(output, check=args.check)
    except (OSError, ValueError) as exc:
        parser.exit(2, f"Cannot prepare sketches: {exc}\n")
    if args.check:
        if changed:
            print("Missing or stale generated files:")
            for path in changed:
                print(f"  {path}")
            print("Run python3 -m tools.prepare_tracker_firmware to refresh sources.")
            return 1
        print("All Arduino sketches are current. User settings were not changed.")
        return 0

    print("Arduino sketches prepared. Existing tracker_config.h settings were preserved.")
    for side, _ in NODES:
        name = f"tracker_{side}"
        print(f"  {side.capitalize()}: {output / name / (name + '.ino')}")
    print("Select ESP32 Dev Module and manually upload each sketch to its matching board.")
    print("Enter the phone hotspot name and password as WIFI_SSID / WIFI_PASSWORD in each")
    print("tracker_config.h tab; the computer joins the same hotspot.")
    print("Each board centers its servo when it starts. No hardware was accessed here.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
